#!/usr/bin/env python3
"""
Deep Evolve evaluation harness — stdout parsing domain.
Auto-generated by deep-evolve. Do not edit during experiment runs.

Runs the project's own command, parses metrics from stdout,
computes a composite score, and outputs standardized format.

Usage: python3 prepare.py [--verbose]
"""

import subprocess, sys, re, os, time
from pathlib import Path

# ── Configuration (filled by deep-evolve init) ──────────────

RAW_COMMAND = "{{RAW_COMMAND}}"
TIMEOUT = {{TIMEOUT}}  # seconds
METRIC_DIRECTION = "{{DIRECTION}}"  # "minimize" or "maximize"
BASELINE_SCORE = None  # deep-evolve init fills this value

# Metrics to extract from stdout: {name: {pattern: regex, weight: float}}
METRICS = {
    # Example: "val_bpb": {"pattern": r"^val_bpb:\s+([\d.]+)", "weight": 1.0},
    {{METRICS_DICT}}
}

# ── Evaluation Engine ───────────────────────────────────────

def run_command():
    """Run the raw command and capture stdout."""
    try:
        result = subprocess.run(
            RAW_COMMAND,
            shell=True,
            capture_output=True,
            text=True,
            timeout=TIMEOUT,
            cwd=str(Path(__file__).parent.parent),  # project root
        )
        return result.stdout, result.stderr, result.returncode
    except subprocess.TimeoutExpired:
        return "", f"TIMEOUT after {TIMEOUT}s", -1
    except Exception as e:
        return "", str(e), -1


def parse_metrics(stdout):
    """Extract metrics from stdout using regex patterns."""
    values = {}
    for name, config in METRICS.items():
        match = re.search(config["pattern"], stdout, re.MULTILINE)
        if match:
            values[name] = float(match.group(1))
    return values


def compute_score(values):
    """Compute weighted composite score from parsed metrics."""
    if not values:
        return 0.0

    score = 0.0
    total_weight = sum(m["weight"] for m in METRICS.values() if m.get("weight"))

    for name, config in METRICS.items():
        if name in values and total_weight > 0:
            normalized = values[name]  # assumes metrics are already in [0,1] or comparable range
            score += (config["weight"] / total_weight) * normalized

    return score


def main():
    verbose = "--verbose" in sys.argv

    stdout, stderr, returncode = run_command()

    if returncode != 0 and returncode != -1:
        if verbose:
            print(f"Command exited with code {returncode}", file=sys.stderr)
            if stderr:
                print(f"stderr: {stderr[:500]}", file=sys.stderr)

    values = parse_metrics(stdout)
    score = compute_score(values)

    if METRIC_DIRECTION == "minimize":
        # Invert so higher score = better (scoring contract: always higher-is-better)
        # baseline → 1.0, improvement → >1.0, regression → <1.0 (no clamp)
        if BASELINE_SCORE is not None and BASELINE_SCORE > 0 and score > 0:
            score = BASELINE_SCORE / score
        elif score == 0:
            score = 1.0

    # Standardized output
    print("\n---")
    print(f"score:              {score:.6f}")
    for name, value in values.items():
        padding = " " * (20 - len(name))
        print(f"{name}:{padding}{value:.6f}")
    print(f"total_scenarios:    {len(METRICS)}")
    print(f"passed_scenarios:   {len(values)}")
    print(f"failed_scenarios:   {len(METRICS) - len(values)}")
    print("---")


if __name__ == "__main__":
    main()
