#!/usr/bin/env python3
"""
Deep Evolve evaluation harness — scenario domain.
Auto-generated by deep-evolve. Do not edit during experiment runs.

Defines test scenarios against the target code, runs each scenario,
computes pass rates per category, and outputs a composite score.

Usage: python3 prepare.py [--verbose]
"""

import subprocess, json, os, sys, tempfile, shutil
from pathlib import Path
from dataclasses import dataclass, field

# ── Configuration (filled by deep-evolve init) ──────────────

PROJECT_ROOT = Path(__file__).parent.parent
TARGET_DIR = PROJECT_ROOT / "{{TARGET_DIR}}"

WEIGHTS = {
    # Example: "hook_reliability": 0.30, "tdd_enforcement": 0.25, ...
    {{WEIGHTS_DICT}}
}
# Normalize
_wsum = sum(WEIGHTS.values())
if _wsum > 0:
    WEIGHTS = {k: v / _wsum for k, v in WEIGHTS.items()}

# ── Scenario Definitions ────────────────────────────────────

@dataclass
class Scenario:
    name: str
    category: str
    description: str
    test_command: str      # bash command to run
    expected_exit: int = 0 # 0=pass, non-0=fail
    expected_output: str = ""  # substring expected in stdout


SCENARIOS = [
    # {{SCENARIOS_LIST}}
    # Example:
    # Scenario(
    #     name="research_blocks_code_edit",
    #     category="hook_reliability",
    #     description="Research phase should block .ts file edits",
    #     test_command="...",
    #     expected_exit=2,
    # ),
]

# ── Node.js Module Tests ────────────────────────────────────

@dataclass
class NodeTest:
    name: str
    category: str
    description: str
    js_expression: str

NODE_TESTS = [
    # {{NODE_TESTS_LIST}}
]

# ── Evaluation Engine ───────────────────────────────────────

def run_scenario(scenario):
    """Run a single scenario. Returns (passed, details)."""
    try:
        result = subprocess.run(
            ["bash", "-c", scenario.test_command],
            capture_output=True, text=True, timeout=10,
            cwd=str(PROJECT_ROOT),
        )
        passed = result.returncode == scenario.expected_exit
        if passed and scenario.expected_output:
            passed = scenario.expected_output in result.stdout
        details = f"exit={result.returncode}(expect={scenario.expected_exit})"
        return passed, details
    except subprocess.TimeoutExpired:
        return False, "TIMEOUT"
    except Exception as e:
        return False, f"EXCEPTION: {e}"


def run_node_test(test):
    """Run a Node.js test. Returns (passed, details)."""
    try:
        result = subprocess.run(
            ["node", "-e", test.js_expression],
            capture_output=True, text=True, timeout=10,
        )
        passed = result.returncode == 0
        details = f"exit={result.returncode}"
        if not passed and result.stderr.strip():
            details += f" err={result.stderr.strip()[:120]}"
        return passed, details
    except subprocess.TimeoutExpired:
        return False, "TIMEOUT"
    except Exception as e:
        return False, f"EXCEPTION: {e}"


def main():
    verbose = "--verbose" in sys.argv
    results_by_category = {}
    total_passed = 0
    total_failed = 0
    failures = []

    all_tests = [(s, "scenario") for s in SCENARIOS] + [(t, "node") for t in NODE_TESTS]

    for test, test_type in all_tests:
        if test_type == "scenario":
            passed, details = run_scenario(test)
        else:
            passed, details = run_node_test(test)

        cat = test.category
        if cat not in results_by_category:
            results_by_category[cat] = {"passed": 0, "total": 0}
        results_by_category[cat]["total"] += 1

        if passed:
            results_by_category[cat]["passed"] += 1
            total_passed += 1
            if verbose:
                print(f"  ✓ {test.name}")
        else:
            total_failed += 1
            failures.append((test.name, test.description, details))
            if verbose:
                print(f"  ✗ {test.name}: {details}")

    category_scores = {}
    for cat, data in results_by_category.items():
        category_scores[cat] = data["passed"] / data["total"] if data["total"] > 0 else 0.0

    score = sum(WEIGHTS.get(cat, 0) * category_scores.get(cat, 0) for cat in WEIGHTS)

    if verbose and failures:
        print(f"\n--- Failures ({total_failed}) ---")
        for name, desc, details in failures:
            print(f"  {name}: {desc}")
            print(f"    {details}")

    print("\n---")
    print(f"score:              {score:.6f}")
    for cat in WEIGHTS:
        val = category_scores.get(cat, 0.0)
        padding = " " * (20 - len(cat))
        print(f"{cat}:{padding}{val:.6f}")
    print(f"total_scenarios:    {total_passed + total_failed}")
    print(f"passed_scenarios:   {total_passed}")
    print(f"failed_scenarios:   {total_failed}")
    print("---")


if __name__ == "__main__":
    main()
