#!/usr/bin/env python3
"""
Deep Evolve evaluation harness — test runner domain.
Auto-generated by deep-evolve. Do not edit during experiment runs.

Runs the project's test suite, measures pass rate and optional coverage,
computes a composite score, and outputs standardized format.

Usage: python3 prepare.py [--verbose]
"""

import subprocess, sys, re, os, json
from pathlib import Path

# ── Configuration (filled by deep-evolve init) ──────────────

TEST_COMMAND = "{{TEST_COMMAND}}"
COVERAGE_COMMAND = "{{COVERAGE_COMMAND}}"  # null if no coverage
TIMEOUT = {{TIMEOUT}}
LINT_COMMAND = "{{LINT_COMMAND}}"  # null if no lint

WEIGHTS = {
    "test_pass_rate": {{TEST_WEIGHT}},
    "coverage": {{COVERAGE_WEIGHT}},
    "lint": {{LINT_WEIGHT}},
}

# ── Evaluation Engine ───────────────────────────────────────

PROJECT_ROOT = str(Path(__file__).parent.parent)


def run_tests():
    """Run test suite and return (passed, total, raw_output)."""
    try:
        result = subprocess.run(
            TEST_COMMAND, shell=True, capture_output=True, text=True,
            timeout=TIMEOUT, cwd=PROJECT_ROOT,
        )
        stdout = result.stdout + result.stderr
        # Parse common test output formats
        # Jest: Tests: X passed, Y total
        jest = re.search(r'Tests:\s+(\d+)\s+passed,\s+(\d+)\s+total', stdout)
        if jest:
            return int(jest.group(1)), int(jest.group(2)), stdout
        # Pytest: X passed, Y failed (or X passed)
        pytest_pass = re.search(r'(\d+)\s+passed', stdout)
        pytest_fail = re.search(r'(\d+)\s+failed', stdout)
        if pytest_pass:
            passed = int(pytest_pass.group(1))
            failed = int(pytest_fail.group(1)) if pytest_fail else 0
            return passed, passed + failed, stdout
        # Generic: count lines with PASS/FAIL
        pass_count = len(re.findall(r'(?:PASS|ok|\.)', stdout))
        fail_count = len(re.findall(r'(?:FAIL|ERROR|F)', stdout))
        total = pass_count + fail_count
        return pass_count, max(total, 1), stdout
    except subprocess.TimeoutExpired:
        return 0, 1, "TIMEOUT"
    except Exception as e:
        return 0, 1, str(e)


def run_coverage():
    """Run coverage command and extract percentage."""
    if not COVERAGE_COMMAND or COVERAGE_COMMAND == "null":
        return None
    try:
        result = subprocess.run(
            COVERAGE_COMMAND, shell=True, capture_output=True, text=True,
            timeout=TIMEOUT, cwd=PROJECT_ROOT,
        )
        stdout = result.stdout + result.stderr
        pct = re.search(r'(\d+(?:\.\d+)?)\s*%', stdout)
        if pct:
            return float(pct.group(1)) / 100.0
        return None
    except Exception:
        return None


def run_lint():
    """Run lint and return (errors, warnings)."""
    if not LINT_COMMAND or LINT_COMMAND == "null":
        return None, None
    try:
        result = subprocess.run(
            LINT_COMMAND, shell=True, capture_output=True, text=True,
            timeout=60, cwd=PROJECT_ROOT,
        )
        error_count = len(re.findall(r'error', result.stdout, re.IGNORECASE))
        warning_count = len(re.findall(r'warning', result.stdout, re.IGNORECASE))
        return error_count, warning_count
    except Exception:
        return None, None


def main():
    verbose = "--verbose" in sys.argv

    passed, total, test_output = run_tests()
    test_rate = passed / total if total > 0 else 0.0
    if verbose:
        print(f"Tests: {passed}/{total} passed ({test_rate:.1%})")

    coverage = run_coverage()
    if verbose and coverage is not None:
        print(f"Coverage: {coverage:.1%}")

    lint_errors, lint_warnings = run_lint()
    lint_score = 1.0
    if lint_errors is not None:
        lint_score = max(0.0, 1.0 - (lint_errors * 0.1 + lint_warnings * 0.02))
    if verbose and lint_errors is not None:
        print(f"Lint: {lint_errors} errors, {lint_warnings} warnings")

    # Compute weighted score
    w = WEIGHTS
    total_weight = sum(v for v in w.values() if v > 0)
    score = 0.0
    if total_weight > 0:
        score += (w["test_pass_rate"] / total_weight) * test_rate
        if coverage is not None:
            score += (w["coverage"] / total_weight) * coverage
        if lint_errors is not None:
            score += (w["lint"] / total_weight) * lint_score

    print("\n---")
    print(f"score:              {score:.6f}")
    print(f"test_pass_rate:     {test_rate:.6f}")
    if coverage is not None:
        print(f"coverage:           {coverage:.6f}")
    if lint_errors is not None:
        print(f"lint_score:         {lint_score:.6f}")
    print(f"total_scenarios:    {total}")
    print(f"passed_scenarios:   {passed}")
    print(f"failed_scenarios:   {total - passed}")
    print("---")


if __name__ == "__main__":
    main()
