#!/usr/bin/env python3
"""
Deep Evolve evaluation harness — stdout parsing domain.
Auto-generated by deep-evolve. Do not edit during experiment runs.

Runs the project's own command, parses metrics from stdout,
computes a composite score, and outputs standardized format.

Usage: python3 prepare.py [--verbose]
"""

import subprocess, sys, re, os, time
from pathlib import Path


def _resolve_project_root():
    """Walk up from this file until we find .deep-evolve/, return its parent.
    Works for both v2.2.0 namespace layout (.deep-evolve/<sid>/prepare.py)
    and legacy flat layout (.deep-evolve/prepare.py)."""
    p = Path(__file__).resolve()
    for ancestor in p.parents:
        if ancestor.name == ".deep-evolve":
            return ancestor.parent
    sys.stderr.write(f"[prepare] WARN: .deep-evolve/ not found in path hierarchy of {p}\n")
    return p.parent


# ── Configuration (filled by deep-evolve init) ──────────────

RAW_COMMAND = "{{RAW_COMMAND}}"
TIMEOUT = {{TIMEOUT}}  # seconds
METRIC_DIRECTION = "{{DIRECTION}}"  # "minimize" or "maximize"
BASELINE_SCORE = None  # deep-evolve init fills this value

# Metrics to extract from stdout: {name: {pattern: regex, weight: float}}
METRICS = {
    # Example: "val_bpb": {"pattern": r"^val_bpb:\s+([\d.]+)", "weight": 1.0},
    {{METRICS_DICT}}
}

# ── Evaluation Engine ───────────────────────────────────────

def run_command():
    """Run the raw command and capture stdout."""
    try:
        result = subprocess.run(
            RAW_COMMAND,
            shell=True,
            capture_output=True,
            text=True,
            timeout=TIMEOUT,
            cwd=str(_resolve_project_root()),  # project root (handles v2.2.0 namespace + legacy flat)
        )
        return result.stdout, result.stderr, result.returncode
    except subprocess.TimeoutExpired:
        return "", f"TIMEOUT after {TIMEOUT}s", -1
    except Exception as e:
        return "", str(e), -1


def parse_metrics(stdout):
    """Extract metrics from stdout using regex patterns."""
    values = {}
    for name, config in METRICS.items():
        match = re.search(config["pattern"], stdout, re.MULTILINE)
        if match:
            values[name] = float(match.group(1))
    return values


def compute_score(values):
    """Compute weighted composite score from parsed metrics."""
    if not values:
        return 0.0

    score = 0.0
    total_weight = sum(m["weight"] for m in METRICS.values() if m.get("weight"))

    for name, config in METRICS.items():
        if name in values and total_weight > 0:
            normalized = values[name]  # assumes metrics are already in [0,1] or comparable range
            score += (config["weight"] / total_weight) * normalized

    return score


def main():
    verbose = "--verbose" in sys.argv

    stdout, stderr, returncode = run_command()

    if returncode != 0 and returncode != -1:
        if verbose:
            print(f"Command exited with code {returncode}", file=sys.stderr)
            if stderr:
                print(f"stderr: {stderr[:500]}", file=sys.stderr)

    values = parse_metrics(stdout)
    score = compute_score(values)
    missing_metrics = len(values) != len(METRICS)

    if METRIC_DIRECTION == "minimize":
        # Scoring contract: higher-is-better.
        # With baseline_raw recorded, minimize metric is inverted so baseline=1.0,
        # improvement>1.0, regression<1.0 (no clamp).
        if missing_metrics:
            score = 0.0
        elif score <= 0:
            # 0 or negative raw: ceiling (infinitely better than baseline).
            # Guards against division-by-zero; 2.0 is arbitrary but bounded downstream.
            score = 2.0 if BASELINE_SCORE is not None else 1.0
        elif BASELINE_SCORE is not None and BASELINE_SCORE > 0:
            score = BASELINE_SCORE / score
        # else: BASELINE_SCORE unset → first-run raw value returned; init.md Step 11
        # writeback (Task 16) will fill BASELINE_SCORE and re-measure to establish 1.0.

    # Standardized output
    print("\n---")
    print(f"score:              {score:.6f}")
    for name, value in values.items():
        padding = " " * (20 - len(name))
        print(f"{name}:{padding}{value:.6f}")
    print(f"total_scenarios:    {len(METRICS)}")
    print(f"passed_scenarios:   {len(values)}")
    print(f"failed_scenarios:   {len(METRICS) - len(values)}")
    print("---")


if __name__ == "__main__":
    main()
